
server:
  port: 7003

spring:
  application:
    name: microservicecloud-eureka-7003
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    hostname: microservicecloud-eureka-7003