server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: gateway-9527.com
info:
  app.name: cloud-wangyong
  company.name: www.wangyong.com
spring:
  application:
    name: microservicecloud-zuul-gateway
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /dept/**
  #ignored-services: microservicecloud-dept
  ignored-services: "*"
  prefix: /wangyong
